### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by marcin-adamczewski** [pusher/pusher-websocket-java#115]
Hello,

We have some crashes related to following exception on version 1.1.2.
It is the same as #97 issue which was fixed in 1.1.2.

`Fatal Exception: java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:788)
       at java.util.HashMap$KeyIterator.next(HashMap.java:815)
       at java.util.AbstractCollection.addAll(AbstractCollection.java:76)
       at com.pusher.client.connection.websocket.WebSocketConnection.updateState(WebSocketConnection.java:148)
       at com.pusher.client.connection.websocket.WebSocketConnection.access$500(WebSocketConnection.java:29)
       at com.pusher.client.connection.websocket.WebSocketConnection$1.run(WebSocketConnection.java:73)
       at com.pusher.client.util.Factory$1.run(Factory.java:105)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)`

Looking forward for fix. Thank you in advance !

**Comment by mochawich** [comment]
Any idea when will the fix be merged? @realtybaron
Thanks

**Comment by dannyroa** [comment]
We are getting this exception too.

**Comment by kn100** [comment]
Closing due to age
