### ISSUE TITLE
Pusher not connecting and giving error in android 4.4

### ISSUE THREAD

**Issue by PratapOdedara** [pusher/pusher-websocket-java#133]
I am trying to connect pusher in android application it is working fine in android 5 but not working in android 4.4 my code is given below

            PusherOptions pOptions = new PusherOptions();
            pOptions.setAuthorizer(new HttpAuthorizer(Constants.PUSHER_AUTH_SRC_URL + "/auth.php"));
            pusher = new Pusher(Constants.PUSHER_KEY, pOptions);
            pusher.connect();

in my gradle file i am using following dependencies
          dependencies {
                compile fileTree(include: ['*.jar'], dir: 'libs')
                testCompile 'junit:junit:4.12'
                compile 'com.android.support:appcompat-v7:23.2.1'
                compile 'com.android.support:design:23.2.1'
                compile 'com.android.support:support-v4:23.2.1'
                compile 'de.hdodenhof:circleimageview:1.2.1'
                compile files('libs/afilechooser.jar')
                compile 'com.google.android.gms:play-services:8.4.0'
                compile 'com.google.android.gms:play-services-gcm:8.4.0'
                compile 'com.pusher:pusher-java-client:1.1.3'
                compile 'com.squareup.picasso:picasso:2.1.1'
                compile 'com.android.support:recyclerview-v7:23.2.1'
                compile 'org.apache.directory.studio:org.apache.commons.io:2.4'
               compile 'org.apache.commons:commons-lang3:3.4'
        }
 
It is giving me error like this 

       FATAL EXCEPTION: main
                                                                Process: com.driversafe, PID: 16960
                                                                java.lang.NoClassDefFoundError: com/pusher/client/util/Factory
                                                                    at com.pusher.client.Pusher.<init>(Pusher.java:83)
                                                                    at   com.driversafe.chat.MessageStatusApiCalling.pusherConnect(MessageStatusApiCalling.java:62)
                                                                    at com.driversafe.chat.ApplicationLifeCycleHandler.onActivityCreated(ApplicationLifeCycleHandler.java:27)
                                                                    at android.app.Application.dispatchActivityCreated(Application.java:189)
                                                                    at android.app.Activity.onCreate(Activity.java:903)
                                                                    at android.support.v4.app.BaseFragmentActivityDonut.onCreate(BaseFragmentActivityDonut.java:39)
                                                                    at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:298)
                                                                    at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)
                                                                    at com.driversafe.SplashActivity.onCreate(SplashActivity.java:57)
                                                                    at android.app.Activity.performCreate(Activity.java:5231)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:136)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                    at dalvik.system.NativeStart.main(Native Method)
                                                                 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.pusher.client.util.Factory" on path: DexPathList[[zip file "/data/app/com.driversafe-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.driversafe-1, /system/lib]]
                                                                    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                    at com.pusher.client.Pusher.<init>(Pusher.java:83) 
                                                                    at com.driversafe.chat.MessageStatusApiCalling.pusherConnect(MessageStatusApiCalling.java:62) 
                                                                    at com.driversafe.chat.ApplicationLifeCycleHandler.onActivityCreated(ApplicationLifeCycleHandler.java:27) 
                                                                    at android.app.Application.dispatchActivityCreated(Application.java:189) 
                                                                    at android.app.Activity.onCreate(Activity.java:903) 
                                                                    at android.support.v4.app.BaseFragmentActivityDonut.onCreate(BaseFragmentActivityDonut.java:39) 
                                                                    at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:298) 
                                                                    at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84) 
                                                                    at com.driversafe.SplashActivity.onCreate(SplashActivity.java:57) 
                                                                    at android.app.Activity.performCreate(Activity.java:5231) 
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:136) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                    at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                    at dalvik.system.NativeStart.main(Native Method) 

Please suggest me solution

**Comment by zmarkan** [comment]
The problem was related to a conflict with a play service dependencies stripping out the Pusher Factory class.
