### ISSUE TITLE
com.pusher.android.notifications.interests.InterestSubscriptionChangeListener.onSubscriptionChangeFailed(int, java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by aya-salama1989** [pusher/pusher-websocket-java#134]
```
java.lang.NullPointerException: Attempt to invoke interface method 'void com.pusher.android.notifications.interests.InterestSubscriptionChangeListener.onSubscriptionChangeFailed(int, java.lang.String)' on a null object reference
                                                                     at com.pusher.android.notifications.PushNotificationRegistration.onFailedRegistration(PushNotificationRegistration.java:194)
                                                                     at com.pusher.android.notifications.tokens.RegistrationListenerStack.onFailedRegistration(RegistrationListenerStack.java:39)
                                                                     at com.pusher.android.notifications.tokens.TokenUploadHandler.onFailure(TokenUploadHandler.java:54)
                                                                     at com.pusher.android.notifications.tokens.TokenUploadHandler.onFailure(TokenUploadHandler.java:44)
                                                                     at com.loopj.android.http.JsonHttpResponseHandler$2$1.run(JsonHttpResponseHandler.java:203)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:155)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5689)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

My onConnectionStateChange fails to complete it's function according to the previous issue

My code is 

 private void pushNotification() {

        PusherAndroidOptions options = new PusherAndroidOptions();
        pusher = new PusherAndroid("a61214d3b60262aaf84a", options);
        pusher.connect(new ConnectionEventListener() {
            @Override
            public void onConnectionStateChange(ConnectionStateChange change) {
                Logging.log("State changed to " + change.getCurrentState() +
                        " from " + change.getPreviousState());
            }

            @Override
            public void onError(String message, String code, Exception e) {
                Logging.log("There was a problem connecting!");
            }
        }, ConnectionState.ALL);

        nativePusher = pusher.nativePusher();

        if (playServicesAvailable()) {
            listener = new PushNotificationRegistrationListener() {
                @Override
                public void onSuccessfulRegistration() {
                    Logging.log("REGISTRATION SUCCESSFUL!!! YEEEEEHAWWWWW!");
                }

                @Override
                public void onFailedRegistration(int statusCode, String response) {
                    Logging.log(
                            "A real sad day. Registration failed with code " + statusCode +
                                    " " + response
                    );
                }
            };

            try {
                    nativePusher.registerFCM(SplashActivity.this, listener);
                    nativePusher.subscribe("notifications");

            } catch (ManifestValidator.InvalidManifestException e) {
                Logging.log("NotificationListener error: " + e.getMessage());
            }
        }
    }

 private boolean playServicesAvailable() {
        GoogleApiAvailability apiAvailability = GoogleApiAvailability.getInstance();
        int resultCode = apiAvailability.isGooglePlayServicesAvailable(this);
        if (resultCode != ConnectionResult.SUCCESS) {
            if (apiAvailability.isUserResolvableError(resultCode)) {
                apiAvailability.getErrorDialog(this, resultCode, PLAY_SERVICES_RESOLUTION_REQUEST)
                        .show();
            } else {
                Log.i(TAG, "This device is not supported.");
                finish();
            }
            return false;
        }
        return true;
    }

##Not pretty sure if it's an issue or my issue as the app was working fine and broke with this issue suddenly, wish i get an answer ASAP as I was supposed to upload my release 24 hrs ago

**Comment by LeoIannacone** [comment]
Any news about this ?

**Comment by zmarkan** [comment]
I recently merged a fix for this  and will be releasing it alongside some other fixes and improvements shortly.

**Comment by zmarkan** [comment]
Was resolved here: https://github.com/pusher/pusher-websocket-android/pull/37
