### ISSUE TITLE
IllegalArgumentException at ConnectionStateChange.java line 21

### ISSUE THREAD

**Issue by jonathanlmarsh** [pusher/pusher-websocket-java#137]
Hi, we are seeing a few of these IllegalArgumentException crashes a day coming from version 1.4.0 of this library and there doesn't appear to be a clear way to avoid them. It looks like WebSocketConnection.java:194 might be missing some error handling. Any help here is appreciated.

```Fatal Exception: java.lang.IllegalArgumentException: Attempted to create an connection state update where both previous and current state are: CONNECTED
       at com.pusher.client.connection.ConnectionStateChange.<init>(ConnectionStateChange.java:21)
       at com.pusher.client.connection.websocket.WebSocketConnection.updateState(WebSocketConnection.java:152)
       at com.pusher.client.connection.websocket.WebSocketConnection.handleConnectionMessage(WebSocketConnection.java:194)
       at com.pusher.client.connection.websocket.WebSocketConnection.handleInternalEvent(WebSocketConnection.java:180)
       at com.pusher.client.connection.websocket.WebSocketConnection.handleEvent(WebSocketConnection.java:171)
       at com.pusher.client.connection.websocket.WebSocketConnection.access$600(WebSocketConnection.java:28)
       at com.pusher.client.connection.websocket.WebSocketConnection$6.run(WebSocketConnection.java:255)
       at com.pusher.client.util.Factory$1.run(Factory.java:103)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by zmarkan** [comment]
Thanks, I can look into this.  Are they coming from Android devices? Any more info you can provide would be great.

**Comment by jonathanlmarsh** [comment]
Yes, they are coming from Android devices, and appears to be distributed across OS versions. This is definitely happening around times when the devices connection state is changing and forcing Pusher to reconnect. We are running Pusher Java Library v1.4.0.

**Comment by zmarkan** [comment]
Hi,
I've added the check that should avoid these issues now. Should be merged, and released in a few days.

https://github.com/pusher/pusher-websocket-java/pull/140

**Comment by jonathanlmarsh** [comment]
Thanks, I'll keep an eye out for it.
