### ISSUE TITLE
Fatal Exception: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by MartyCatawiki** [pusher/pusher-websocket-java#139]
In Crashlytics this is our number 1 crash with the latest version 1.4.0. Would be nice to solve it to get our crash-free rate higher.

`Fatal Exception: java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
       at java.util.HashMap$ValueIterator.next(HashMap.java:879)
       at com.pusher.client.channel.impl.ChannelManager.onConnectionStateChange(ChannelManager.java:120)
       at com.pusher.client.connection.websocket.WebSocketConnection$4.run(WebSocketConnection.java:163)
       at com.pusher.client.util.Factory$1.run(Factory.java:103)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)`

**Comment by zmarkan** [comment]
Thanks, I'll look into that. 
This is happening on Android, I presume?

**Comment by MartyCatawiki** [comment]
Yes @zmarkan you're right, it's for Android! I appreciate that you will look into that, thanks.

**Comment by zmarkan** [comment]
Presume this happens when subscribe/unsubscribe is triggered at the same time as a connection is established. https://github.com/pusher/pusher-websocket-java/pull/142 should fix it.

**Comment by MartyCatawiki** [comment]
Thanks for solving @zmarkan, the ConcurrentModificationException does not occur anymore with version 1.5.0
