### ISSUE TITLE
onAuthenticationFailure(): java.io.FileNotFoundException

### ISSUE THREAD

**Issue by mukeshsolanki** [pusher/pusher-websocket-java#162]
### What is the issue?
 I use pusher-websocket-java to subscribe a private channel, and it throws the below error.
Here is my code
``` 
  initializePusher(@NonNull String accessToken, @Nullable String channelName,
      PrivateChannelEventListener channelEventListener) {
    mChannelEventListener = channelEventListener;
    mPusher = new Pusher(BuildConfig.PUSHER_API_KEY, buildPusherOptions(accessToken));
    if (channelName != null) {
      mPrivateChannel =
          mPusher.subscribePrivate(channelName, mChannelEventListener, EVENTS_TO_BIND);
    }
  }

  private PusherOptions buildPusherOptions(@NonNull String accessToken) {
    HttpAuthorizer authorizer = new HttpAuthorizer(AUTH_URL);
    HashMap<String, String> authHeader = new HashMap<>();
    authHeader.put(ACCESS_TOKEN, accessToken);
    authorizer.setHeaders(authHeader);
    return new PusherOptions().setAuthorizer(authorizer);
  }
```

### Is it a crash report? Submit stack traces or anything that you think would help
```
com.pusher.client.AuthorizationFailureException: java.io.FileNotFoundException: <AUTH_URL>
    at com.pusher.client.util.HttpAuthorizer.authorize(HttpAuthorizer.java:149)
    at com.pusher.client.channel.impl.PrivateChannelImpl.getAuthResponse(PrivateChannelImpl.java:121)
    at com.pusher.client.channel.impl.PrivateChannelImpl.toSubscribeMessage(PrivateChannelImpl.java:88)
    at com.pusher.client.channel.impl.ChannelManager$1.run(ChannelManager.java:140)
    at com.pusher.client.util.Factory$1.run(Factory.java:103)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:761)
 Caused by: java.io.FileNotFoundException:  <AUTH_URL>
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:250)
    at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
    at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
    at com.pusher.client.util.HttpAuthorizer.authorize(HttpAuthorizer.java:131)
    at com.pusher.client.channel.impl.PrivateChannelImpl.getAuthResponse(PrivateChannelImpl.java:121) 
    at com.pusher.client.channel.impl.PrivateChannelImpl.toSubscribeMessage(PrivateChannelImpl.java:88) 
    at com.pusher.client.channel.impl.ChannelManager$1.run(ChannelManager.java:140) 
    at com.pusher.client.util.Factory$1.run(Factory.java:103) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
    at java.lang.Thread.run(Thread.java:761) 
```
CC @pusher/mobile

**Comment by mukeshsolanki** [comment]
Any update on this guys?

**Comment by zmarkan** [comment]
Hi there!
This looks like the authorizer is returning something that it's not expecting. Can you check in your backend logs for what status code your authorize endpoint is returning?

Thanks

**Comment by mukeshsolanki** [comment]
The back end is responding with a `200 ok` but that's not the issue the request does not go through and fails before that. i.e the request does not reach our server and error pops up before that.

**Comment by zmarkan** [comment]
So if I understand correctly the authorizer request doesn't reach your server at all? 
This could be an endpoint issue - could you double check that please?

**Comment by mukeshsolanki** [comment]
Yes, the authorizer request doesn't reach your server at all. We have double checked our endpoint just to be sure and we are still receiving this error.

**Comment by zmarkan** [comment]
Hmmm this might be a server SDK issue - which one are you using?

**Comment by mukeshsolanki** [comment]
We are using `pusher-0.15.2` ruby on rails gem on our server. It's most likely not a server issue as I mentioned the request does not seem to be reaching our rails server. We have tried to authenticate using postman and found that the request authenticates properly. Here is the postman log

```
POST /api/v2/notifications/authorize HTTP/1.1
Host: www.mycustomdomain.com
X-Access-Token: <AccessToken to our rails server>
Cache-Control: no-cache

{
 "channel_name": "private-channel-123",
 "socket_id": "<socket id>"
}


Response 200 OK

{"auth":"valid token"}
```

**Comment by mukeshsolanki** [comment]
We seemed to have fixed the issue by adding 
```
authHeader.put("Content-Type", "application/x-www-form-urlencoded");
authHeader.put("Accept", "application/json");
```
to the headers thanks for your help @zmarkan

**Comment by malik082009** [comment]
@mukeshsolanki i am still getting onAuthenticationFailure(): java.io.FileNotFoundException
i have tried all the possible solutions.
Exception has been thrown on this line
 // Read response
            final InputStream is = connection.getInputStream();
in `HttpAuthorizer`
