### ISSUE TITLE
java.io.IOException: Pong reply not received (code 4201)

### ISSUE THREAD

**Issue by cowwoc** [pusher/pusher-websocket-java#188]
Version 1.8.1

My pusher client randomly threw the following error when communicating with the bitstamp.net server:

```
java.io.IOException: Pong reply not received (code 4201)
	at com.mycompany.AbstractWebsocketStream$2.onError(AbstractWebsocketStream.java:272)
	at com.pusher.client.connection.websocket.WebSocketConnection$5.run(WebSocketConnection.java:238)
	at com.pusher.client.util.Factory$1.run(Factory.java:109)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

Why would this happen? It implies that the client (my side) is at fault but I haven't done anything to prevent pusher from responding with a pong. Any ideas?

CC @pusher/mobile

**Comment by kn100** [comment]
It's possible you just had a connection issue temporarily. If you see these frequently, you can try adjusting the ping/pong interval time, and if you still see them let me know!

**Comment by elverkilde** [comment]
Closing this due to inactivity. Feel free to re-open if you're still experiencing this issue.
