### ISSUE TITLE
com.pusher.client.AuthorizationFailureException: java.io.IOException: Server returned HTTP response code: 401 for URL:

### ISSUE THREAD

**Issue by makarid** [pusher/pusher-websocket-java#222]
### What is the issue?
When i connect to a private channel everything is ok and the connection successful. If for some reason an exception occurs in the channel and pusher tries to reconnect, the reconnection will fail with this error: com.pusher.client.AuthorizationFailureException: java.io.IOException: Server returned HTTP response code: 401 for URL:. This will continue indefinitely.
... 

### Is it a crash report? Submit stack traces or anything that you think would help
17:06:53.816 [pusher-java-client eventQueue] ERROR info.bitrich.xchangestream.service.pusher.PusherStreamingService - java.io.IOException: Server returned HTTP response code: 401 for URL: https://www.coinmate.io/api/pusherAuth
com.pusher.client.AuthorizationFailureException: java.io.IOException: Server returned HTTP response code: 401 for URL: https://www.coinmate.io/api/pusherAuth
	at com.pusher.client.util.HttpAuthorizer.authorize(HttpAuthorizer.java:146) ~[pusher-java-client-2.0.0.jar:2.0.0]
	at com.pusher.client.channel.impl.PrivateChannelImpl.getAuthResponse(PrivateChannelImpl.java:121) ~[pusher-java-client-2.0.0.jar:2.0.0]
	at com.pusher.client.channel.impl.PrivateChannelImpl.toSubscribeMessage(PrivateChannelImpl.java:88) ~[pusher-java-client-2.0.0.jar:2.0.0]
	at com.pusher.client.channel.impl.ChannelManager$1.run(ChannelManager.java:140) ~[pusher-java-client-2.0.0.jar:2.0.0]
	at com.pusher.client.util.Factory$1.run(Factory.java:109) [pusher-java-client-2.0.0.jar:2.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://www.coinmate.io/api/pusherAuth
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894) ~[?:1.8.0_151]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_151]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263) ~[?:1.8.0_151]
	at com.pusher.client.util.HttpAuthorizer.authorize(HttpAuthorizer.java:128) ~[pusher-java-client-2.0.0.jar:2.0.0]
	... 7 more
...

### Any improvements you suggest
I am converting the response of the host to Reactor.Flux and i have add the retry() operator in order to retry indefinitely. Here is the implementation that i have on the PusherStreamingExchange.class: 

 private static final Logger LOG = LoggerFactory.getLogger(PusherStreamingService.class);

    private final Pusher pusher;

    public PusherStreamingService(String apiKey) {
        pusher = new Pusher(apiKey);
    }

    public PusherStreamingService(String apiKey, String cluster) {
        PusherOptions options = new PusherOptions();
        options.setCluster(cluster);
        pusher = new Pusher(apiKey, options);
    }

    public PusherStreamingService(String apiKey, String cluster, Authorizer authorizer) {
        PusherOptions options = new PusherOptions();
        options.setCluster(cluster);
        options.setAuthorizer(authorizer);
        this.pusher = new Pusher(apiKey, options);
    }

    /**
     * Testing constructor
     */
    protected PusherStreamingService(Pusher pusher) {
        this.pusher = pusher;
    }

    @Override
    protected Completable openConnection() {
        return Completable.create(e -> pusher.connect(new ConnectionEventListener() {
            @Override
            public void onConnectionStateChange(ConnectionStateChange change) {
                LOG.info("State changed to " + change.getCurrentState() +
                        " from " + change.getPreviousState());
                if (ConnectionState.CONNECTED.equals(change.getCurrentState())) {
                    e.onComplete();
                }
            }

            @Override
            public void onError(String message, String code, Exception throwable) {
                if (throwable != null) {
                    e.onError(throwable);
                } else {
                    e.onError(new RuntimeException("No exception found: [code: " + code + "], message: " + message));
                }
            }
        }, ConnectionState.ALL));
    }

    public Completable disconnect() {
        return Completable.create(completable -> {
            pusher.disconnect();
            completable.onComplete();
        });
    }

    public Observable<String> subscribePrivateChannel(String channelName, String eventName) {
        return this.subscribePrivateChannel(channelName, Collections.singletonList(eventName));
    }

    public Observable<String> subscribeChannel(String channelName, String eventName) {
        return subscribeChannel(channelName, Collections.singletonList(eventName));
    }

    public Observable<String> subscribeChannel(String channelName, List<String> eventsName) {
        LOG.info("Subscribing to channel {}.", channelName);
        return Observable.<String>create(e -> {
            if (!ConnectionState.CONNECTED.equals(pusher.getConnection().getState())) {
                e.onError(new NotConnectedException());
                return;
            }
            Channel channel = pusher.subscribe(channelName);

            for (String event : eventsName) {
                channel.bind(event, (pusherEvent) -> {
                    LOG.debug("Incoming data: {}", pusherEvent.getData());
                    e.onNext(pusherEvent.getData());
                });
            }
        }).doOnDispose(() -> pusher.unsubscribe(channelName));
    }

    public Observable<String> subscribePrivateChannel(String channelName, List<String> eventsName) {
        LOG.info("Subscribing to channel {}.", channelName);

        return Observable.<String>create(e -> {
            if (!ConnectionState.CONNECTED.equals(pusher.getConnection().getState())) {
                e.onError(new NotConnectedException());
                return;
            }

            PrivateChannelEventListener listener = new PrivateChannelEventListener() {
                public void onAuthenticationFailure(String s, Exception ex) {
                    LOG.error(ex.getMessage(), ex);
                    e.onError(ex);
                }

                public void onSubscriptionSucceeded(String s) {
                    LOG.info("Subscription successful! :{} ", s);
                }

                @Override
                public void onEvent(PusherEvent pusherEvent) {
                    LOG.debug("Incoming data: {}", pusherEvent.getData());
                    e.onNext(pusherEvent.getData());
                }
            };
            Channel channel = pusher.subscribePrivate(channelName,listener);
            for (String event : eventsName) {
                channel.bind(event, listener);
            }
        }).doOnDispose(() -> {
            LOG.info("Disposing " + channelName);
            pusher.unsubscribe(channelName);
        });
    }

    public boolean isSocketOpen() {
        return pusher.getConnection().getState() == ConnectionState.CONNECTED;
    }

    public void useCompressedMessages(boolean compressedMessages) { throw new UnsupportedOperationException(); }
...

---- 

CC @pusher/mobile

**Comment by makarid** [comment]
FIxed
