### ISSUE TITLE
SSL Handskake error on devices with Android lollipop & below

### ISSUE THREAD

**Issue by bikranttripathi** [pusher/pusher-websocket-java#231]
We recently started experiencing an issue with devices using Lollipop & below unable to connect to pusher socket. After investigating we found that it was happening because pusher connection was failing with `SSLHandshakeException`.

```
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@16089013@16.0.89 (020700-239467275):43)
	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.waitForHandshake(:com.google.android.gms@16089013@16.0.89 (020700-239467275):1)
	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.getInputStream(:com.google.android.gms@16089013@16.0.89 (020700-239467275):5)
	at com.google.android.gms.org.conscrypt.KitKatPlatformOpenSSLSocketImplAdapter.getInputStream(:com.google.android.gms@16089013@16.0.89 (020700-239467275))
	at com.pusher.java_websocket.client.WebSocketClient.run(WebSocketClient.java:166)
	at java.lang.Thread.run(Thread.java:818)
 Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:318)
	at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:219)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.google.android.gms.org.conscrypt.Platform.checkTrusted(:com.google.android.gms@16089013@16.0.89 (020700-239467275):2)
	at com.google.android.gms.org.conscrypt.Platform.checkServerTrusted(:com.google.android.gms@16089013@16.0.89 (020700-239467275):3)
	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(:com.google.android.gms@16089013@16.0.89 (020700-239467275):12)
	at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.google.android.gms.org.conscrypt.NativeSsl.doHandshake(:com.google.android.gms@16089013@16.0.89 (020700-239467275):7)
at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@16089013@16.0.89 (020700-239467275):14)
	... 5 more
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	... 15 more
```

I managed to successfully connect to Pusher by setting PusherOptions.setEncryption(false) however, I would prefer using SSL connection if it's possible.

I'm using `v1.8.0` of `pusher-java-client`.

Is there anyway we can make it work with SSL?

CC @pusher/mobile

**Comment by elverkilde** [comment]
This was happening because the older Android devices haven't received security updates for years, including updated CA root certificates. We have fixed this by adding intermediate certificates matching the root certificates on these older devices.

We are looking into various intermediate certificates which will keep these devices running for a few more years. However, you may want to look into updating the root certificates on the device(s).
