### ISSUE TITLE
AuthorizationFailureException due to null `userId`

### ISSUE THREAD

**Issue by scottyab** [pusher/pusher-websocket-java#260]
### What is the issue?

[PresenceChannelImpl.extractUserIdFromChannelData()](https://github.com/pusher/pusher-websocket-java/blob/6b47cc4f5f5f17bc5df73c00381ffe1f16059522/src/main/java/com/pusher/client/channel/impl/PresenceChannelImpl.java#L166) is throwing a `AuthorizationFailureException` as the userId is null. I appreciate this might have been the intention of this method but I'm trying to understand why this constitutes an AuthorizationFailureException? 

We have a scenario where the user is anonymous and so doesn't have a userId. We've found this works when connecting via Javascript client (maybe by accident?) so I'm wondering can we remove the throwing of AuthorizationFailureException when userId is null?  

Maybe there's some side effect I'm not aware of but seems not throwing due to userId=null would mean `PresenceChannelImpl.myUserID` is null, `PresenceChannelImpl.getMe()` would return null and `PresenceChannelImpl.getUsers()` would return an empty list. 

interface PresenceChannel.getMe() isn't marked as @nullable so that could be an issue 😨  

Or is there an alternative solution you would recommend? 

Thanks! 

### Is it a crash report? Submit stack traces or anything that you think would help

```
PusherPresenceChannelEventListener: Presence onAuthenticationFailure Invalid response from Authorizer: no user_id key in channel_data object: null
    com.pusher.client.AuthorizationFailureException: Invalid response from Authorizer: no user_id key in channel_data object: null
        at com.pusher.client.channel.impl.PresenceChannelImpl.extractUserIdFromChannelData(PresenceChannelImpl.java:177)
        at com.pusher.client.channel.impl.PresenceChannelImpl.toSubscribeMessage(PresenceChannelImpl.java:71)
        at com.pusher.client.channel.impl.ChannelManager$1.run(ChannelManager.java:140)
        at com.pusher.client.util.Factory$1.run(Factory.java:109)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

### Any improvements you suggest

Don't throw a `AuthorizationFailureException` 👍 🙇 

---- 

CC @pusher/mobile

**Comment by scottyab** [comment]
Hey @daniellevass hope you're well (especially during the 😷 ) - do you have any insight to this issue we're seeing? feels like there could be a difference in behaviour between pusher-js - pusher worker and the pusher-websocket-java SDK. (or maybe I'm doing something wrong?).

Thanks

**Comment by scottyab** [comment]
Sorry this was my bad. Turns out since we recently switched to Kotlin Moshi our @field:Json("channel_data") wasn't being processed so this meant `channel_data` was being delivered to the Pusher SDK as null. We fixed this by removing field prefix `@Json("channel_data")` now it's working as expected.
