### ISSUE TITLE
NoSuchMethodError: No interface method in class Ljava/util/Map

### ISSUE THREAD

**Issue by Nuclominus** [pusher/pusher-websocket-java#267]
Hi! I use last version of lib - "com.pusher:pusher-java-client:2.2.1" and get this error on android 6.0.1 when server push event. On android 7 and higher works fine.  

all compatibility set in 1.8 version 
```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8
    }
```

This is logs:
```
E/AndroidRuntime: FATAL EXCEPTION: pusher-java-client eventQueue
    Process: frendly.go.gofrendly.dev, PID: 21098
    java.lang.NoSuchMethodError: No interface method replace(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Ljava/util/Map; or its super classes (declaration of 'java.util.Map' appears in /system/framework/core-libart.jar)
        at com.pusher.client.channel.impl.PrivateEncryptedChannelImpl.decryptMessage(PrivateEncryptedChannelImpl.java:188)
        at com.pusher.client.channel.impl.PrivateEncryptedChannelImpl.prepareEvent(PrivateEncryptedChannelImpl.java:134)
        at com.pusher.client.channel.impl.ChannelImpl.onMessage(ChannelImpl.java:105)
        at com.pusher.client.channel.impl.ChannelManager.onMessage(ChannelManager.java:116)
        at com.pusher.client.connection.websocket.WebSocketConnection.handleEvent(WebSocketConnection.java:177)
        at com.pusher.client.connection.websocket.WebSocketConnection.access$600(WebSocketConnection.java:27)
        at com.pusher.client.connection.websocket.WebSocketConnection$6.run(WebSocketConnection.java:261)
        at com.pusher.client.util.Factory$1.run(Factory.java:119)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```
It seems that the method "replace" does not find in the interface of Map in decryptMessage function. I don't use any rules in proguard what could cause such an effect

---- 

CC @pusher/mobile

**Comment by Nuclominus** [comment]
I find solution. Problem was in android studio 5 with build gradle 4.0.0. For gradle 4+ need use D8/R8 desugaring
more detail on [android developer](https://developer.android.com/studio/write/java8-support#library-desugaring)

in compile options need enable coreLibraryDesugaring

```
compileOptions {
    // Flag to enable support for the new language APIs
    coreLibraryDesugaringEnabled true
    // Sets Java compatibility to Java 8
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
}

dependencies {
  coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.0.5'
}
```
