### ISSUE TITLE
 java.lang.IllegalArgumentException: Already subscribed to a channel with name private-user.5

### ISSUE THREAD

**Issue by willBars** [pusher/pusher-websocket-java#301]
I don not known  happend this error 
   

   `java.lang.IllegalArgumentException: Already subscribed to a channel with name private-user.5
        at com.pusher.client.channel.impl.ChannelManager.validateArgumentsAndBindEvents(ChannelManager.java:198)
        at com.pusher.client.channel.impl.ChannelManager.subscribeTo(ChannelManager.java:85)
        at com.pusher.client.Pusher.subscribePrivate(Pusher.java:285)
        at com.xuyang.sdk.utils.EventUtil$4.onConnectionStateChange(EventUtil.java:265)
        at com.pusher.client.connection.websocket.WebSocketConnection$4.run(WebSocketConnection.java:166)
        at com.pusher.client.util.Factory$1.run(Factory.java:119)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)`

i socket can Send and receive  notication , but Not sure when happend this error,please Teach me how to avoid this mistake

**Comment by benw-pusher** [comment]
This error would occur when you attempt to subscribe to a channel to which the client already has an active subscription. You should check whether your code is subscribing to the same channel in multiple places and prevent this. 
If you need anything more then it is best to follow up with support as this does not look like a library issue but instead an implementation issue. You can log requests via https://support.pusher.com/hc/en-us/requests/new
