### ISSUE TITLE
IllegalArgumentException on connection

### ISSUE THREAD

**Issue by sarthakgandhidunzo** [pusher/pusher-websocket-java#321]
### What is the issue?

Getting this crash on android apps:

Pusher Library version for android - 'com.pusher:pusher-java-client:1.8.2'

Device: Redmi Note 9
OS : 11

### Is it a crash report? Submit stack traces or anything that you think would help

```
Fatal Exception: java.lang.IllegalArgumentException
Attempted to create an connection state update where both previous and current state are: DISCONNECTED
com.pusher.client.connection.ConnectionStateChange.<init> (ConnectionStateChange.java:21)
com.pusher.client.connection.websocket.WebSocketConnection.updateState (WebSocketConnection.java:155)
com.pusher.client.connection.websocket.WebSocketConnection.access$200 (WebSocketConnection.java:27)
com.pusher.client.connection.websocket.WebSocketConnection$8.run (WebSocketConnection.java:322)
com.pusher.client.util.Factory$1.run (Factory.java:109)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:923) 
```

CC @pusher/mobile

**Comment by benw-pusher** [comment]
I haven't received a response so I will close this out - feel free to reopen with more info.

**Comment by abhishekdubey331** [comment]
We are also facing the same issue and the number of crashes is quite hight,

`Fatal Exception: java.lang.IllegalArgumentException: Attempted to create an connection state update where both previous and current state are: DISCONNECTED
       at com.pusher.client.connection.ConnectionStateChange.<init>(ConnectionStateChange.java:21)
       at com.pusher.client.connection.websocket.WebSocketConnection.updateState(WebSocketConnection.java:155)
       at com.pusher.client.connection.websocket.WebSocketConnection.access$200(WebSocketConnection.java:27)
       at com.pusher.client.connection.websocket.WebSocketConnection$8.run(WebSocketConnection.java:312)
       at com.pusher.client.util.Factory$1.run(Factory.java:109)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)`

**Comment by abhishekdubey331** [comment]
Please reopen the issue.
