### ISSUE TITLE
Proxy settings not working

### ISSUE THREAD

**Issue by apouche** [pusher/pusher-websocket-java#356]
### What is the issue?
I'm trying to use Proxyman (macOS) to intercept pusher traffic. However this just simply doesn't work on the Android emulator. I've tried many different configuration options (with or without TLS), with `DIRECT` (`NO_PROXY`), `HTTP` and `SOCKS` and it always fails with different errors.

Here are my findings:

#### DIRECT
With a `DIRECT` (`NO_PROXY`) proxy the connection never establishes (connection state goes from DISCONNECTED to CONNECTING) and eventually fails with:

```
java.net.ConnectException: failed to connect to ws-eu.pusher.com/34.255.229.199 (port 443) from /:: (port 58482): connect failed: ECONNREFUSED (Connection refused)
at libcore.io.IoBridge.connect(IoBridge.java:188)
at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
```

#### HTTP
With `HTTP` Proxy if I enable TLS I see the same thing it looks like proxy settings are simply bypassed when using TLS.
If I disable TLS I get

```
java.lang.IllegalArgumentException: Invalid Proxy
at java.net.Socket.<init>(Socket.java:155)
at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:384)
at java.lang.Thread.run(Thread.java:920)
```

This seems like [an issue with old version of Java](https://stackoverflow.com/questions/8816292/unable-to-get-proxy-working-with-socket). However I tried upgrading the Android JDK to 11 or even 17 but it's still the same issue.

#### SOCKS
With `SOCKS` and TLS enabled I still get the same error:

```
java.net.ConnectException: failed to connect to ws-eu.pusher.com/34.255.229.199 (port 443) from /:: (port 58482): connect failed: ECONNREFUSED (Connection refused)
at libcore.io.IoBridge.connect(IoBridge.java:188)
at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
```

and If disable TLS I just never get any error but the connection never establishes either.

Here's how the proxy is setup:
```kotlin
class CorePusher {
  private lateinit var pusher: Pusher

  init {
    val options = PusherOptions()
    options.setCluster("eu")
    options.isUseTLS = false

    thread {
      options.proxy = Proxy(Proxy.Type.SOCKS, InetSocketAddress("192.168.1.16",9090))
//
      android.os.Handler(Looper.getMainLooper()).post {
        pusher = Pusher("324a5892f058e9192173", options)
        pusher.connect(object : ConnectionEventListener {
          override fun onConnectionStateChange(change: ConnectionStateChange?) {
            Log.i(tagName, "pusher connection state changed from ${change?.previousState?.name} to ${change?.currentState?.name}")
          }

          override fun onError(message: String?, code: String?, e: Exception?) {
            Log.e(tagName, "failed to connect to pusher: $message")
            e?.let {
              Log.e(tagName, it.stackTraceToString())
            }
          }
        })
      }
    }
  }
}
```

Any help would be greatly appreciated.

CC @pusher/mobile

**Comment by apouche** [comment]
Yes I can confirm I did, the proxy is working and I do see the traffic between app & server. Just not over websockets.

**Comment by benw-pusher** [comment]
I have not been able to configure apps to work with Proxyman - however I have verified that the proxy settings are respected and work by using a different proxy application. When using Charles Proxy the app works as expected, connecting to the Channels service without error and the traffic shows in the Charles UI proxy logs as expected. This indicates the issue is with Proxyman and not with our library.
