### ISSUE TITLE
When change network status puhser crash

### ISSUE THREAD

**Issue by abora97** [pusher/pusher-websocket-java#361]
### What is the issue?

... when the network disconnect pusher crash and states change from connected to reconnecting pusher crash the app.

###  crash report

`FATAL EXCEPTION: pusher-java-client eventQueue
                                                                                                    Process: com.surepay.softmada, PID: 11997
                                                                                                    java.lang.NullPointerException: Parameter specified as non-null is null: method com.surepay.softmada.features.home.pusherNotification.PusherHandler$pusherConnect$1.onError, parameter code
                                                                                                    	at com.surepay.softmada.features.home.pusherNotification.PusherHandler$pusherConnect$1.onError(Unknown Source:13)
                                                                                                    	at com.pusher.client.connection.websocket.WebSocketConnection.lambda$sendErrorToAllListeners$4(WebSocketConnection.java:197)
                                                                                                    	at com.pusher.client.connection.websocket.WebSocketConnection$$ExternalSyntheticLambda1.run(Unknown Source:8)
                                                                                                    	at com.pusher.client.util.Factory.lambda$queueOnEventThread$0(Factory.java:140)
                                                                                                    	at com.pusher.client.util.Factory$$ExternalSyntheticLambda0.run(Unknown Source:2)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:920)`

CC @pusher/mobile

**Comment by abora97** [comment]
`object PusherHandler {
    private lateinit var pusher: Pusher
    private const val TAG = "PusherHandler"

    fun initPusher(context: Context) {
        Timber.tag(TAG).e("******** init pusher ********")
        val options = PusherOptions().apply {
            setCluster("eu")
            maxReconnectionAttempts = Int.MAX_VALUE
            maxReconnectGapInSeconds = 30
        }
        pusher = Pusher("c9d951f7fce7b24456b8", options)
        pusherEvents(context)
    }

    fun pusherConnect() {
        pusher.connect(object : ConnectionEventListener {
            override fun onConnectionStateChange(change: ConnectionStateChange) {
                Timber.tag(TAG)
                    .e("State changed from ${change.previousState} to ${change.currentState}")
                if (change.currentState == ConnectionState.RECONNECTING) {
                    pusher.disconnect()
                }

            }

            override fun onError(
                message: String,
                code: String,
                e: Exception
            ) {
                Timber.tag(TAG)
                    .e("There was a problem connecting! code ($code), message ($message), exception($e)")
            }
        }, ConnectionState.ALL)

    }

    fun pusherDisconnect() {
        pusher.disconnect()
    }

    private fun pusherEvents(context: Context) {
        val pusherChannel = pusher.subscribe("notification-channel")
        pusherChannel.bind("notification-message") { event ->
            Timber.tag(TAG)
                .e("Received event with data: $event")
            NotificationBuilder(context).buildNotification(
                event.data.toString()
            )

        }
    }

}`

**Comment by benw-pusher** [comment]
Could you change the onError to allow the message parameter to be nullable? This should help resolve the issue. 

```
For example: 
override fun onError(
            message: String,
            code: String,
            e: Exception
        )
```
        
Would become
```

override fun onError(
            message: String?,
            code: String,
            e: Exception
        )

```
