### ISSUE TITLE
IllegalArgumentException in ConnectionStateChange

### ISSUE THREAD

**Issue by mrsasha** [pusher/pusher-websocket-java#54]
Hi, lately I've been seeing more and more of these and I don't see any way to stop them because they're inside your library. I already check the state and have put connect/disconnect calls inside try/catch.

Here's the complete stacktrace:
`java.lang.IllegalArgumentException: Attempted to create an connection state update where both previous and current state are: CONNECTING
	at com.pusher.client.connection.ConnectionStateChange.<init>(ConnectionStateChange.java:20)
	at com.pusher.client.connection.websocket.WebSocketConnection.updateState(WebSocketConnection.java:131)
	at com.pusher.client.connection.websocket.WebSocketConnection.access$400(WebSocketConnection.java:26)
	at com.pusher.client.connection.websocket.WebSocketConnection$1.run(WebSocketConnection.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)`

Looking at your code, in WebSocketConnection.java you have an unchecked call from handleConnectionMessage and I think that's the culprit. 

Do you know how I could prevent these from happening? We already have 2 crashes a day for this.

Thanks,
Sasa

**Comment by lifedemons** [comment]
I have the same issue and it happens continuously, please, pay attention on it

**Comment by zimbatm** [comment]
@mdpye can you have a look at this ?

**Comment by mdpye** [comment]
Hi @lifedemons 

The line numbers in the stacktrace which @mrsasha provided don't match up with master, could you provide a stacktrace and the version of the library which you are using?

**Comment by lifedemons** [comment]
Hi @mdpye 
Version:
    compile 'com.pusher:pusher-java-client:0.3.3'
Stacktrace:
java.lang.IllegalArgumentException: Attempted to create an connection state update where both previous and current state are: CONNECTING
	at com.pusher.client.connection.ConnectionStateChange.<init>(ConnectionStateChange.java:20)
	at com.pusher.client.connection.websocket.WebSocketConnection.updateState(WebSocketConnection.java:131)
	at com.pusher.client.connection.websocket.WebSocketConnection.access$400(WebSocketConnection.java:26)
	at com.pusher.client.connection.websocket.WebSocketConnection$1.run(WebSocketConnection.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

Thank you in advance.

**Comment by LukasKr** [comment]
@mdpye any updates here?

**Comment by LukasKr** [comment]
@zimbatm, @mdpye?

**Comment by mdpye** [comment]
Based on a reading of the code, this situation looks pretty unlikely.

The state is only changed to `CONNECTING` in exactly one place in the library. That place is guarded by a check that the old state is `DISCONNECTED`, and all calls are serialised on to a single thread.

A log of the connection state changes up to the point of the error might be useful. I don't think it's going to be resolved without being able to replicate it.

**Comment by namdp** [comment]
I have the same issue and it happens continuously and affect a lots of my users. I have read the library source code and understand what

**Comment by gsalgun** [comment]
Hello @mdpye,

Recently this error started appearing in our crash logs. We can't handle this error since it's in your library code. We want to provide a crash-free experience to users and this is something we can't solve by ourselves.

Please handle it inside the library. Thanks.

**Comment by jpatel531** [comment]
@mrsasha @namdp @lifedemons @LukasKr  @gsalgun 

I'm working on this and hope to have a fix out ASAP. I was wondering if you could share how you have set up Pusher? Are you opening connections in an activity or a background service? Do you have any custom reconnection logic? Are you guaranteed _only one_ Pusher instance *and* one Pusher connection active at a given time?
