### ISSUE TITLE
java.util.ConcurrentModificationException Crash

### ISSUE THREAD

**Issue by nbarraille** [pusher/pusher-websocket-java#69]
Hi,
We're seeing this issue in Crashlytics on some occasions. Of course we can't really reproduce it locally as this is a concurrency issue:
Any idea what's going on?
```
java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:806)
       at java.util.HashMap$KeyIterator.next(HashMap.java:833)
       at java.util.AbstractCollection.addAll(AbstractCollection.java:76)
       at com.pusher.client.connection.websocket.WebSocketConnection.updateState(WebSocketConnection.java:135)
       at com.pusher.client.connection.websocket.WebSocketConnection.access$400(WebSocketConnection.java:26)
       at com.pusher.client.connection.websocket.WebSocketConnection$1.run(WebSocketConnection.java:63)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)
```

Thanks!

**Comment by nbarraille** [comment]
We are still seeing the same issue on 0.3.3

**Comment by tjohn** [comment]
I get the same stack trace as well. 

```java
java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
       at java.util.HashMap$KeyIterator.next(HashMap.java:814)
       at com.pusher.client.channel.impl.ChannelImpl.onMessage(ChannelImpl.java:93)
       at com.pusher.client.channel.impl.ChannelManager.onMessage(ChannelManager.java:76)
       at com.pusher.client.connection.websocket.WebSocketConnection.handleEvent(WebSocketConnection.java:152)
       at com.pusher.client.connection.websocket.WebSocketConnection.access$600(WebSocketConnection.java:26)
       at com.pusher.client.connection.websocket.WebSocketConnection$6.run(WebSocketConnection.java:230)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```
