### ISSUE TITLE
UnresolvedAddressException with WebSocket library

### ISSUE THREAD

**Issue by ocram** [pusher/pusher-websocket-java#7]
I cannot tell the exact steps to reproduce this, but my Android application crashes for a great number of users with the following Exception:

```
java.nio.channels.UnresolvedAddressException
at java.nio.SocketChannelImpl.validateAddress(SocketChannelImpl.java:422)
at java.nio.SocketChannelImpl.connect(SocketChannelImpl.java:154)
at org.java_websocket.client.WebSocketClient.void run()(SourceFile:188)
at java.lang.Thread.run(Thread.java:856)java.nio.channels.UnresolvedAddressException
at java.nio.SocketChannelImpl.validateAddress(SocketChannelImpl.java:422)
at java.nio.SocketChannelImpl.connect(SocketChannelImpl.java:154)
at org.java_websocket.client.WebSocketClient.void run()(SourceFile:188)
at java.lang.Thread.run(Thread.java:856)
```

And there's no way to handle this yet.

I'm not sure how this is affected by this issue and its solution:
https://github.com/leggetter/pusher-java-client/issues/8

For this problem, that solution does not seem to work, at least.

**Comment by RahimRahimov** [comment]
check this: http://stackoverflow.com/a/40498520/4576879
