### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by natangr** [pusher/pusher-websocket-java#97]
Hi,

I'm still getting ConcurrentModificationException on version 1.0.2. 
It happened twice today. 

First time:
`Fatal Exception: java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
       at java.util.HashMap$KeyIterator.next(HashMap.java:814)
       at java.util.AbstractCollection.addAll(AbstractCollection.java:76)
       at com.pusher.client.connection.websocket.WebSocketConnection.sendErrorToAllListeners(WebSocketConnection.java:208)
       at com.pusher.client.connection.websocket.WebSocketConnection.access$500(WebSocketConnection.java:27)
       at com.pusher.client.connection.websocket.WebSocketConnection$8.run(WebSocketConnection.java:272)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)`

Second time:
`Fatal Exception: java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
       at java.util.HashMap$KeyIterator.next(HashMap.java:814)
       at java.util.AbstractCollection.addAll(AbstractCollection.java:76)
       at com.pusher.client.connection.websocket.WebSocketConnection.updateState(WebSocketConnection.java:140)
       at com.pusher.client.connection.websocket.WebSocketConnection.access$400(WebSocketConnection.java:27)
       at com.pusher.client.connection.websocket.WebSocketConnection$1.run(WebSocketConnection.java:65)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)`

**Comment by jpatel531** [comment]
@mdpye should I lock [this](https://github.com/pusher/pusher-websocket-java/blob/master/src/main/java/com/pusher/client/connection/websocket/WebSocketConnection.java#L36) to be locked, just like we did [here](https://github.com/pusher/pusher-websocket-java/blob/master/src/main/java/com/pusher/client/channel/impl/ChannelImpl.java#L59) ?

**Comment by mdpye** [comment]
If we can ensure nothing else will be locked during access to it, possibly, yes.

There's also https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ConcurrentHashMap.html

**Comment by natangr** [comment]
Any estimates on when this fix will be merged into master?

**Comment by natangr** [comment]
Any updates?
