### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by natangr** [pusher/pusher-websocket-java#98]
Hi guys,

I had a report of another crash on the version 1.0.2:
`Fatal Exception: java.lang.IllegalArgumentException: Attempted to create an connection state update where both previous and current state are: CONNECTING
       at com.pusher.client.connection.ConnectionStateChange.<init>(ConnectionStateChange.java:21)
       at com.pusher.client.connection.websocket.WebSocketConnection.updateState(WebSocketConnection.java:136)
       at com.pusher.client.connection.websocket.WebSocketConnection.access$400(WebSocketConnection.java:27)
       at com.pusher.client.connection.websocket.WebSocketConnection$1.run(WebSocketConnection.java:65)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)`

**Comment by gsalgun** [comment]
Hello,

Recently this error started appearing in our crash logs. We can't handle this error since it's in your library code. We want to provide a crash-free experience to users and this is something we can't solve by ourselves.

Please handle it inside the library. Thanks.

**Comment by jpatel531** [comment]
Currently working on it!
